jquants:
  plan: light
  earliest_supported_date:
    free: 2024-01-01
    light: 2021-05-01
  plans:
    free:
      requests_per_minute: 5
      parallel_fetch: false
    light:
      requests_per_minute: 60
      parallel_fetch: true
      max_parallel_requests: 4
